SHOW search_path;
SET search_path = "shop";

DROP TABLE IF EXISTS customers_products;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS products;

CREATE TABLE customers (
                           id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name varchar(20) NOT NULL UNIQUE
);

CREATE TABLE products (
                          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name varchar(30) NOT NULL UNIQUE,
                          price numeric(4, 2) NOT NULL
);

CREATE TABLE customers_products (
                                    customer_id integer NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
                                    product_id integer NOT NULL REFERENCES products (id) ON DELETE CASCADE,
                                    price numeric(4, 2) NOT NULL DEFAULT 0.0
);

CREATE INDEX customer_name_idx ON customers (name);
CREATE INDEX product_name_idx ON customers (name);

insert into customers (name)
values
    ('John'),
    ('Jack'),
    ('Mike'),
    ('Kate');

insert into products (name, price)
values
    ('Snickers', 39.99),
    ('Cola', 29.99),
    ('Juice', 49.99),
    ('Bread', 14.99);


