DROP TABLE IF EXISTS items;

CREATE TABLE items(
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    val integer,
    version bigint default 0
);

INSERT INTO items (val)
VALUES
    (0),(0),(0),(0),(0),(0),(0),(0),(0),(0),
    (0),(0),(0),(0),(0),(0),(0),(0),(0),(0),
    (0),(0),(0),(0),(0),(0),(0),(0),(0),(0),
    (0),(0),(0),(0),(0),(0),(0),(0),(0),(0);